# Generated by Django 4.1.4 on 2022-12-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_audio_alter_post_id_alter_song_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
